package rebue.suc.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import rebue.robotech.mapper.MybatisBaseMapper;
import rebue.suc.mo.SucLoginLogMo;

@Mapper
public interface SucLoginLogMapper extends MybatisBaseMapper<SucLoginLogMo, Long> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_LOGIN_LOG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_LOGIN_LOG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    int insert(SucLoginLogMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_LOGIN_LOG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    int insertSelective(SucLoginLogMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_LOGIN_LOG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    SucLoginLogMo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_LOGIN_LOG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    int updateByPrimaryKeySelective(SucLoginLogMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_LOGIN_LOG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    int updateByPrimaryKey(SucLoginLogMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_LOGIN_LOG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    List<SucLoginLogMo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_LOGIN_LOG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    List<SucLoginLogMo> selectSelective(SucLoginLogMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_LOGIN_LOG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    boolean existByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_LOGIN_LOG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    boolean existSelective(SucLoginLogMo record);
}