package rebue.suc.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import rebue.robotech.mapper.MybatisBaseMapper;
import rebue.suc.mo.SucLockLogMo;

@Mapper
public interface SucLockLogMapper extends MybatisBaseMapper<SucLockLogMo, Long> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_LOCK_LOG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_LOCK_LOG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    int insert(SucLockLogMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_LOCK_LOG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    int insertSelective(SucLockLogMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_LOCK_LOG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    SucLockLogMo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_LOCK_LOG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    int updateByPrimaryKeySelective(SucLockLogMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_LOCK_LOG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    int updateByPrimaryKey(SucLockLogMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_LOCK_LOG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    List<SucLockLogMo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_LOCK_LOG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    List<SucLockLogMo> selectSelective(SucLockLogMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_LOCK_LOG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    boolean existByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_LOCK_LOG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    boolean existSelective(SucLockLogMo record);
}