package rebue.suc.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import rebue.robotech.mapper.MybatisBaseMapper;
import rebue.suc.mo.SucOpLogMo;

@Mapper
public interface SucOpLogMapper extends MybatisBaseMapper<SucOpLogMo, Long> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_OP_LOG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_OP_LOG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    int insert(SucOpLogMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_OP_LOG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    int insertSelective(SucOpLogMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_OP_LOG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    SucOpLogMo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_OP_LOG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    int updateByPrimaryKeySelective(SucOpLogMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_OP_LOG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    int updateByPrimaryKey(SucOpLogMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_OP_LOG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    List<SucOpLogMo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_OP_LOG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    List<SucOpLogMo> selectSelective(SucOpLogMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_OP_LOG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    boolean existByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_OP_LOG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    boolean existSelective(SucOpLogMo record);
}