package rebue.suc.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import rebue.robotech.mapper.MybatisBaseMapper;
import rebue.suc.mo.SucRegMo;

@Mapper
public interface SucRegMapper extends MybatisBaseMapper<SucRegMo, Long> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_REG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_REG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    int insert(SucRegMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_REG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    int insertSelective(SucRegMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_REG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    SucRegMo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_REG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    int updateByPrimaryKeySelective(SucRegMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_REG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    int updateByPrimaryKey(SucRegMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_REG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    List<SucRegMo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_REG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    List<SucRegMo> selectSelective(SucRegMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_REG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    boolean existByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_REG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    boolean existSelective(SucRegMo record);
}