spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/suc?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: suc
    password: 123456
  redis:
    # 最大实例数
    maxTotal: 100
    # 最大空闲实例数
    maxIdle: 10
    # (创建实例时)最大等待时间
    maxWaitMillis: 10000
    # (创建实例时)是否验证
    testOnBorrow: false
    # 集群类型 (Single,RedisCluster)
    clusterType: Single
    # Single类型需要配置连接Redis的host和port
    host: 127.0.0.1
    port: 6379
    # 集群类型需要配置服务器的节点
    #clusterNodes: 
    #  - 192.168.1.201:7000
    #  - 192.168.1.201:7001
    #  - 192.168.1.201:7002
    #  - 192.168.1.201:7003
    #  - 192.168.1.201:7004
    #  - 192.168.1.201:7005
    # 集群类型需要配置连接超时
    #connectionTimeout: 5000
    # 集群类型需要配置返回值的超时时间
    #soTimeout: 5000
    # 集群类型需要配置出现异常最大重试次数
    #maxAttempts: 5