package rebue.suc.mo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * Database Table Remarks:
 *   用户锁定日志
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table SUC_LOCK_LOG
 *
 * @mbg.generated do_not_delete_during_merge 2018-02-25 16:21:26
 */
@ApiModel(value = "SucLockLogMo", description = "用户锁定日志")
@JsonInclude(Include.NON_NULL)
public class SucLockLogMo implements Serializable {
    /**
     * Database Column Remarks:
     *   用户锁定日志ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_LOCK_LOG.ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "用户锁定日志ID")
    private Long id;

    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_LOCK_LOG.USER_ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "用户ID")
    private Long userId;

    /**
     * Database Column Remarks:
     *   锁定原因
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_LOCK_LOG.LOCK_REASON
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "锁定原因")
    private String lockReason;

    /**
     * Database Column Remarks:
     *   锁定时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_LOCK_LOG.LOCK_TIME
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "锁定时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date lockTime;

    /**
     * Database Column Remarks:
     *   锁定操作员ID，0为系统操作
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_LOCK_LOG.LOCK_OP_ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "锁定操作员ID，0为系统操作")
    private Long lockOpId;

    /**
     * Database Column Remarks:
     *   解锁原因
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_LOCK_LOG.UNLOCK_REASON
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "解锁原因")
    private String unlockReason;

    /**
     * Database Column Remarks:
     *   解锁时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_LOCK_LOG.UNLOCK_TIME
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "解锁时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date unlockTime;

    /**
     * Database Column Remarks:
     *   解锁操作员ID，0为系统操作
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_LOCK_LOG.UNLOCK_OP_ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "解锁操作员ID，0为系统操作")
    private Long unlockOpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SUC_LOCK_LOG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_LOCK_LOG.ID
     *
     * @return the value of SUC_LOCK_LOG.ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_LOCK_LOG.ID
     *
     * @param id the value for SUC_LOCK_LOG.ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_LOCK_LOG.USER_ID
     *
     * @return the value of SUC_LOCK_LOG.USER_ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_LOCK_LOG.USER_ID
     *
     * @param userId the value for SUC_LOCK_LOG.USER_ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_LOCK_LOG.LOCK_REASON
     *
     * @return the value of SUC_LOCK_LOG.LOCK_REASON
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public String getLockReason() {
        return lockReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_LOCK_LOG.LOCK_REASON
     *
     * @param lockReason the value for SUC_LOCK_LOG.LOCK_REASON
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setLockReason(String lockReason) {
        this.lockReason = lockReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_LOCK_LOG.LOCK_TIME
     *
     * @return the value of SUC_LOCK_LOG.LOCK_TIME
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public Date getLockTime() {
        return lockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_LOCK_LOG.LOCK_TIME
     *
     * @param lockTime the value for SUC_LOCK_LOG.LOCK_TIME
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setLockTime(Date lockTime) {
        this.lockTime = lockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_LOCK_LOG.LOCK_OP_ID
     *
     * @return the value of SUC_LOCK_LOG.LOCK_OP_ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public Long getLockOpId() {
        return lockOpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_LOCK_LOG.LOCK_OP_ID
     *
     * @param lockOpId the value for SUC_LOCK_LOG.LOCK_OP_ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setLockOpId(Long lockOpId) {
        this.lockOpId = lockOpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_LOCK_LOG.UNLOCK_REASON
     *
     * @return the value of SUC_LOCK_LOG.UNLOCK_REASON
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public String getUnlockReason() {
        return unlockReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_LOCK_LOG.UNLOCK_REASON
     *
     * @param unlockReason the value for SUC_LOCK_LOG.UNLOCK_REASON
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setUnlockReason(String unlockReason) {
        this.unlockReason = unlockReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_LOCK_LOG.UNLOCK_TIME
     *
     * @return the value of SUC_LOCK_LOG.UNLOCK_TIME
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public Date getUnlockTime() {
        return unlockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_LOCK_LOG.UNLOCK_TIME
     *
     * @param unlockTime the value for SUC_LOCK_LOG.UNLOCK_TIME
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setUnlockTime(Date unlockTime) {
        this.unlockTime = unlockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_LOCK_LOG.UNLOCK_OP_ID
     *
     * @return the value of SUC_LOCK_LOG.UNLOCK_OP_ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public Long getUnlockOpId() {
        return unlockOpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_LOCK_LOG.UNLOCK_OP_ID
     *
     * @param unlockOpId the value for SUC_LOCK_LOG.UNLOCK_OP_ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setUnlockOpId(Long unlockOpId) {
        this.unlockOpId = unlockOpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_LOCK_LOG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", lockReason=").append(lockReason);
        sb.append(", lockTime=").append(lockTime);
        sb.append(", lockOpId=").append(lockOpId);
        sb.append(", unlockReason=").append(unlockReason);
        sb.append(", unlockTime=").append(unlockTime);
        sb.append(", unlockOpId=").append(unlockOpId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_LOCK_LOG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SucLockLogMo other = (SucLockLogMo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
        ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_LOCK_LOG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}