package rebue.suc.mo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * Database Table Remarks:
 *   用户登录日志
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table SUC_LOGIN_LOG
 *
 * @mbg.generated do_not_delete_during_merge 2018-02-25 16:21:26
 */
@ApiModel(value = "SucLoginLogMo", description = "用户登录日志")
@JsonInclude(Include.NON_NULL)
public class SucLoginLogMo implements Serializable {
    /**
     * Database Column Remarks:
     *   用户登录日志ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_LOGIN_LOG.ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "用户登录日志ID")
    private Long id;

    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_LOGIN_LOG.USER_ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "用户ID")
    private Long userId;

    /**
     * Database Column Remarks:
     *   操作时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_LOGIN_LOG.OP_TIME
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "操作时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date opTime;

    /**
     * Database Column Remarks:
     *   登录类型(与注册类型一致)
     *               1: 用户登录名
     *               2: 电子邮箱
     *               3: 手机
     *               4: QQ
     *               5: 微信
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_LOGIN_LOG.LOGIN_TYPE
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "登录类型(与注册类型一致)\n"
             +"            1: 用户登录名\n"
             +"            2: 电子邮箱\n"
             +"            3: 手机\n"
             +"            4: QQ\n"
             +"            5: 微信")
    private Byte loginType;

    /**
     * Database Column Remarks:
     *   应用ID
     *               标记是通过哪个应用系统登录的编码，要与注册的应用ID意义一致
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_LOGIN_LOG.APP_ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "应用ID\n"
             +"            标记是通过哪个应用系统登录的编码，要与注册的应用ID意义一致")
    private Byte appId;

    /**
     * Database Column Remarks:
     *   浏览器类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_LOGIN_LOG.USER_AGENT
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "浏览器类型")
    private String userAgent;

    /**
     * Database Column Remarks:
     *   IP地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_LOGIN_LOG.IP
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "IP地址")
    private String ip;

    /**
     * Database Column Remarks:
     *   MAC地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_LOGIN_LOG.MAC
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "MAC地址")
    private String mac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SUC_LOGIN_LOG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_LOGIN_LOG.ID
     *
     * @return the value of SUC_LOGIN_LOG.ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_LOGIN_LOG.ID
     *
     * @param id the value for SUC_LOGIN_LOG.ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_LOGIN_LOG.USER_ID
     *
     * @return the value of SUC_LOGIN_LOG.USER_ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_LOGIN_LOG.USER_ID
     *
     * @param userId the value for SUC_LOGIN_LOG.USER_ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_LOGIN_LOG.OP_TIME
     *
     * @return the value of SUC_LOGIN_LOG.OP_TIME
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public Date getOpTime() {
        return opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_LOGIN_LOG.OP_TIME
     *
     * @param opTime the value for SUC_LOGIN_LOG.OP_TIME
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setOpTime(Date opTime) {
        this.opTime = opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_LOGIN_LOG.LOGIN_TYPE
     *
     * @return the value of SUC_LOGIN_LOG.LOGIN_TYPE
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public Byte getLoginType() {
        return loginType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_LOGIN_LOG.LOGIN_TYPE
     *
     * @param loginType the value for SUC_LOGIN_LOG.LOGIN_TYPE
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setLoginType(Byte loginType) {
        this.loginType = loginType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_LOGIN_LOG.APP_ID
     *
     * @return the value of SUC_LOGIN_LOG.APP_ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public Byte getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_LOGIN_LOG.APP_ID
     *
     * @param appId the value for SUC_LOGIN_LOG.APP_ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setAppId(Byte appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_LOGIN_LOG.USER_AGENT
     *
     * @return the value of SUC_LOGIN_LOG.USER_AGENT
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public String getUserAgent() {
        return userAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_LOGIN_LOG.USER_AGENT
     *
     * @param userAgent the value for SUC_LOGIN_LOG.USER_AGENT
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_LOGIN_LOG.IP
     *
     * @return the value of SUC_LOGIN_LOG.IP
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_LOGIN_LOG.IP
     *
     * @param ip the value for SUC_LOGIN_LOG.IP
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_LOGIN_LOG.MAC
     *
     * @return the value of SUC_LOGIN_LOG.MAC
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public String getMac() {
        return mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_LOGIN_LOG.MAC
     *
     * @param mac the value for SUC_LOGIN_LOG.MAC
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setMac(String mac) {
        this.mac = mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_LOGIN_LOG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", opTime=").append(opTime);
        sb.append(", loginType=").append(loginType);
        sb.append(", appId=").append(appId);
        sb.append(", userAgent=").append(userAgent);
        sb.append(", ip=").append(ip);
        sb.append(", mac=").append(mac);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_LOGIN_LOG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SucLoginLogMo other = (SucLoginLogMo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
        ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_LOGIN_LOG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}