package rebue.suc.mo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * Database Table Remarks:
 *   用户操作日志
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table SUC_OP_LOG
 *
 * @mbg.generated do_not_delete_during_merge 2018-02-25 16:21:26
 */
@ApiModel(value = "SucOpLogMo", description = "用户操作日志")
@JsonInclude(Include.NON_NULL)
public class SucOpLogMo implements Serializable {
    /**
     * Database Column Remarks:
     *   用户操作日志ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_OP_LOG.ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "用户操作日志ID")
    private Long id;

    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_OP_LOG.USER_ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "用户ID")
    private Long userId;

    /**
     * Database Column Remarks:
     *   操作类型
     *               1:修改登录密码;
     *               2:修改支付密码;
     *               3:绑定QQ登录;
     *               4:绑定微信登录;
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_OP_LOG.OP_TYPE
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "操作类型\n"
             +"            1:修改登录密码;\n"
             +"            2:修改支付密码;\n"
             +"            3:绑定QQ登录;\n"
             +"            4:绑定微信登录;")
    private Byte opType;

    /**
     * Database Column Remarks:
     *   操作时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_OP_LOG.OP_TIME
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "操作时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date opTime;

    /**
     * Database Column Remarks:
     *   操作详情
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_OP_LOG.OP_DETAIL
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "操作详情")
    private String opDetail;

    /**
     * Database Column Remarks:
     *   应用ID
     *               标记是哪个应用系统来注册的编码，要与登录应用ID意义一致
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_OP_LOG.APP_ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "应用ID\n"
             +"            标记是哪个应用系统来注册的编码，要与登录应用ID意义一致")
    private Byte appId;

    /**
     * Database Column Remarks:
     *   浏览器类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_OP_LOG.USER_AGENT
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "浏览器类型")
    private String userAgent;

    /**
     * Database Column Remarks:
     *   MAC地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_OP_LOG.MAC
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "MAC地址")
    private String mac;

    /**
     * Database Column Remarks:
     *   IP地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_OP_LOG.IP
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "IP地址")
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SUC_OP_LOG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_OP_LOG.ID
     *
     * @return the value of SUC_OP_LOG.ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_OP_LOG.ID
     *
     * @param id the value for SUC_OP_LOG.ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_OP_LOG.USER_ID
     *
     * @return the value of SUC_OP_LOG.USER_ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_OP_LOG.USER_ID
     *
     * @param userId the value for SUC_OP_LOG.USER_ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_OP_LOG.OP_TYPE
     *
     * @return the value of SUC_OP_LOG.OP_TYPE
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public Byte getOpType() {
        return opType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_OP_LOG.OP_TYPE
     *
     * @param opType the value for SUC_OP_LOG.OP_TYPE
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setOpType(Byte opType) {
        this.opType = opType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_OP_LOG.OP_TIME
     *
     * @return the value of SUC_OP_LOG.OP_TIME
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public Date getOpTime() {
        return opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_OP_LOG.OP_TIME
     *
     * @param opTime the value for SUC_OP_LOG.OP_TIME
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setOpTime(Date opTime) {
        this.opTime = opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_OP_LOG.OP_DETAIL
     *
     * @return the value of SUC_OP_LOG.OP_DETAIL
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public String getOpDetail() {
        return opDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_OP_LOG.OP_DETAIL
     *
     * @param opDetail the value for SUC_OP_LOG.OP_DETAIL
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setOpDetail(String opDetail) {
        this.opDetail = opDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_OP_LOG.APP_ID
     *
     * @return the value of SUC_OP_LOG.APP_ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public Byte getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_OP_LOG.APP_ID
     *
     * @param appId the value for SUC_OP_LOG.APP_ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setAppId(Byte appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_OP_LOG.USER_AGENT
     *
     * @return the value of SUC_OP_LOG.USER_AGENT
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public String getUserAgent() {
        return userAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_OP_LOG.USER_AGENT
     *
     * @param userAgent the value for SUC_OP_LOG.USER_AGENT
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_OP_LOG.MAC
     *
     * @return the value of SUC_OP_LOG.MAC
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public String getMac() {
        return mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_OP_LOG.MAC
     *
     * @param mac the value for SUC_OP_LOG.MAC
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setMac(String mac) {
        this.mac = mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_OP_LOG.IP
     *
     * @return the value of SUC_OP_LOG.IP
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_OP_LOG.IP
     *
     * @param ip the value for SUC_OP_LOG.IP
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_OP_LOG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", opType=").append(opType);
        sb.append(", opTime=").append(opTime);
        sb.append(", opDetail=").append(opDetail);
        sb.append(", appId=").append(appId);
        sb.append(", userAgent=").append(userAgent);
        sb.append(", mac=").append(mac);
        sb.append(", ip=").append(ip);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_OP_LOG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SucOpLogMo other = (SucOpLogMo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
        ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_OP_LOG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}