package rebue.suc.mo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * Database Table Remarks:
 *   用户注册
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table SUC_REG
 *
 * @mbg.generated do_not_delete_during_merge 2018-02-25 16:21:26
 */
@ApiModel(value = "SucRegMo", description = "用户注册")
@JsonInclude(Include.NON_NULL)
public class SucRegMo implements Serializable {
    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_REG.ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "用户ID")
    private Long id;

    /**
     * Database Column Remarks:
     *   注册时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_REG.REG_TIME
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "注册时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date regTime;

    /**
     * Database Column Remarks:
     *   注册类型(与登录类型一致)
     *                           1: 用户登录名
     *                           2: 电子邮箱
     *                           3: 手机
     *                           4: QQ
     *                           5: 微信
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_REG.REG_TYPE
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "注册类型(与登录类型一致)\n"
             +"                        1: 用户登录名\n"
             +"                        2: 电子邮箱\n"
             +"                        3: 手机\n"
             +"                        4: QQ\n"
             +"                        5: 微信")
    private Byte regType;

    /**
     * Database Column Remarks:
     *   推广者ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_REG.PROMOTER_ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "推广者ID")
    private Long promoterId;

    /**
     * Database Column Remarks:
     *   应用ID
     *               标记是哪个应用系统来注册的编码，要与登录应用ID意义一致
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_REG.APP_ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "应用ID\n"
             +"            标记是哪个应用系统来注册的编码，要与登录应用ID意义一致")
    private Byte appId;

    /**
     * Database Column Remarks:
     *   浏览器类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_REG.USER_AGENT
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "浏览器类型")
    private String userAgent;

    /**
     * Database Column Remarks:
     *   MAC地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_REG.MAC
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "MAC地址")
    private String mac;

    /**
     * Database Column Remarks:
     *   IP地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_REG.IP
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "IP地址")
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SUC_REG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_REG.ID
     *
     * @return the value of SUC_REG.ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_REG.ID
     *
     * @param id the value for SUC_REG.ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_REG.REG_TIME
     *
     * @return the value of SUC_REG.REG_TIME
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_REG.REG_TIME
     *
     * @param regTime the value for SUC_REG.REG_TIME
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_REG.REG_TYPE
     *
     * @return the value of SUC_REG.REG_TYPE
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public Byte getRegType() {
        return regType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_REG.REG_TYPE
     *
     * @param regType the value for SUC_REG.REG_TYPE
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setRegType(Byte regType) {
        this.regType = regType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_REG.PROMOTER_ID
     *
     * @return the value of SUC_REG.PROMOTER_ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public Long getPromoterId() {
        return promoterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_REG.PROMOTER_ID
     *
     * @param promoterId the value for SUC_REG.PROMOTER_ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setPromoterId(Long promoterId) {
        this.promoterId = promoterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_REG.APP_ID
     *
     * @return the value of SUC_REG.APP_ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public Byte getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_REG.APP_ID
     *
     * @param appId the value for SUC_REG.APP_ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setAppId(Byte appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_REG.USER_AGENT
     *
     * @return the value of SUC_REG.USER_AGENT
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public String getUserAgent() {
        return userAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_REG.USER_AGENT
     *
     * @param userAgent the value for SUC_REG.USER_AGENT
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_REG.MAC
     *
     * @return the value of SUC_REG.MAC
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public String getMac() {
        return mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_REG.MAC
     *
     * @param mac the value for SUC_REG.MAC
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setMac(String mac) {
        this.mac = mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_REG.IP
     *
     * @return the value of SUC_REG.IP
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_REG.IP
     *
     * @param ip the value for SUC_REG.IP
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_REG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", regTime=").append(regTime);
        sb.append(", regType=").append(regType);
        sb.append(", promoterId=").append(promoterId);
        sb.append(", appId=").append(appId);
        sb.append(", userAgent=").append(userAgent);
        sb.append(", mac=").append(mac);
        sb.append(", ip=").append(ip);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_REG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SucRegMo other = (SucRegMo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
        ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_REG
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}