package rebue.suc.mo;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

/**
 * Database Table Remarks:
 *   用户信息
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table SUC_USER
 *
 * @mbg.generated do_not_delete_during_merge 2018-02-25 16:21:26
 */
@ApiModel(value = "SucUserMo", description = "用户信息")
@JsonInclude(Include.NON_NULL)
public class SucUserMo implements Serializable {
    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_USER.ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "用户ID")
    private Long id;

    /**
     * Database Column Remarks:
     *   登录账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_USER.LOGIN_NAME
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "登录账号")
    private String loginName;

    /**
     * Database Column Remarks:
     *   登录密码
     *               登录密码=小写(MD5(小写(MD5(密码明文))+小写(密码组合码)))
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_USER.LOGIN_PSWD
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "登录密码\n"
             +"            登录密码=小写(MD5(小写(MD5(密码明文))+小写(密码组合码)))")
    private String loginPswd;

    /**
     * Database Column Remarks:
     *   支付密码
     *               用户的支付密码默认和登录密码一致
     *               保存在字段的计算方法如下：
     *               MD5(数据库存储的已加密的登录密码)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_USER.PAY_PSWD
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "支付密码\n"
             +"            用户的支付密码默认和登录密码一致\n"
             +"            保存在字段的计算方法如下：\n"
             +"            MD5(数据库存储的已加密的登录密码)")
    private String payPswd;

    /**
     * Database Column Remarks:
     *   密码组合码
     *               与密码组合加密用
     *               登录密码=小写(MD5(小写(MD5(密码明文))+小写(密码组合码)))
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_USER.SALT
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "密码组合码\n"
             +"            与密码组合加密用\n"
             +"            登录密码=小写(MD5(小写(MD5(密码明文))+小写(密码组合码)))")
    private String salt;

    /**
     * Database Column Remarks:
     *   昵称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_USER.NICKNAME
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "昵称")
    private String nickname;

    /**
     * Database Column Remarks:
     *   头像
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_USER.FACE
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "头像")
    private String face;

    /**
     * Database Column Remarks:
     *   实名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_USER.REALNAME
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "实名")
    private String realname;

    /**
     * Database Column Remarks:
     *   是否已验证实名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_USER.IS_VERIFIED_REALNAME
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "是否已验证实名")
    private Boolean isVerifiedRealname;

    /**
     * Database Column Remarks:
     *   身份证号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_USER.IDCARD
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "身份证号")
    private String idcard;

    /**
     * Database Column Remarks:
     *   是否已验证身份证号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_USER.IS_VERIFIED_IDCARD
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "是否已验证身份证号")
    private Boolean isVerifiedIdcard;

    /**
     * Database Column Remarks:
     *   电子邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_USER.EMAIL
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "电子邮箱")
    private String email;

    /**
     * Database Column Remarks:
     *   是否已验证电子邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_USER.IS_VERIFIED_EMAIL
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "是否已验证电子邮箱")
    private Boolean isVerifiedEmail;

    /**
     * Database Column Remarks:
     *   手机
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_USER.MOBILE
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "手机")
    private String mobile;

    /**
     * Database Column Remarks:
     *   是否已验证手机号码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_USER.IS_VERIFIED_MOBILE
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "是否已验证手机号码")
    private Boolean isVerifiedMobile;

    /**
     * Database Column Remarks:
     *   QQ的ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_USER.QQ_ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "QQ的ID")
    private String qqId;

    /**
     * Database Column Remarks:
     *   QQ昵称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_USER.QQ_NICKNAME
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "QQ昵称")
    private String qqNickname;

    /**
     * Database Column Remarks:
     *   QQ头像
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_USER.QQ_FACE
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "QQ头像")
    private String qqFace;

    /**
     * Database Column Remarks:
     *   微信的ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_USER.WX_ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "微信的ID")
    private String wxId;

    /**
     * Database Column Remarks:
     *   微信昵称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_USER.WX_NICKNAME
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "微信昵称")
    private String wxNickname;

    /**
     * Database Column Remarks:
     *   微信头像
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_USER.WX_FACE
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "微信头像")
    private String wxFace;

    /**
     * Database Column Remarks:
     *   是否锁定
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_USER.IS_LOCK
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "是否锁定")
    private Boolean isLock;

    /**
     * Database Column Remarks:
     *   修改时间戳(添加或更新本条记录时的时间戳)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_USER.MODIFIED_TIMESTAMP
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "修改时间戳(添加或更新本条记录时的时间戳)")
    private Long modifiedTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SUC_USER
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_USER.ID
     *
     * @return the value of SUC_USER.ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_USER.ID
     *
     * @param id the value for SUC_USER.ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_USER.LOGIN_NAME
     *
     * @return the value of SUC_USER.LOGIN_NAME
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_USER.LOGIN_NAME
     *
     * @param loginName the value for SUC_USER.LOGIN_NAME
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_USER.LOGIN_PSWD
     *
     * @return the value of SUC_USER.LOGIN_PSWD
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public String getLoginPswd() {
        return loginPswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_USER.LOGIN_PSWD
     *
     * @param loginPswd the value for SUC_USER.LOGIN_PSWD
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setLoginPswd(String loginPswd) {
        this.loginPswd = loginPswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_USER.PAY_PSWD
     *
     * @return the value of SUC_USER.PAY_PSWD
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public String getPayPswd() {
        return payPswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_USER.PAY_PSWD
     *
     * @param payPswd the value for SUC_USER.PAY_PSWD
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setPayPswd(String payPswd) {
        this.payPswd = payPswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_USER.SALT
     *
     * @return the value of SUC_USER.SALT
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_USER.SALT
     *
     * @param salt the value for SUC_USER.SALT
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setSalt(String salt) {
        this.salt = salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_USER.NICKNAME
     *
     * @return the value of SUC_USER.NICKNAME
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_USER.NICKNAME
     *
     * @param nickname the value for SUC_USER.NICKNAME
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_USER.FACE
     *
     * @return the value of SUC_USER.FACE
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public String getFace() {
        return face;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_USER.FACE
     *
     * @param face the value for SUC_USER.FACE
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setFace(String face) {
        this.face = face;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_USER.REALNAME
     *
     * @return the value of SUC_USER.REALNAME
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_USER.REALNAME
     *
     * @param realname the value for SUC_USER.REALNAME
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setRealname(String realname) {
        this.realname = realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_USER.IS_VERIFIED_REALNAME
     *
     * @return the value of SUC_USER.IS_VERIFIED_REALNAME
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public Boolean getIsVerifiedRealname() {
        return isVerifiedRealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_USER.IS_VERIFIED_REALNAME
     *
     * @param isVerifiedRealname the value for SUC_USER.IS_VERIFIED_REALNAME
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setIsVerifiedRealname(Boolean isVerifiedRealname) {
        this.isVerifiedRealname = isVerifiedRealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_USER.IDCARD
     *
     * @return the value of SUC_USER.IDCARD
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_USER.IDCARD
     *
     * @param idcard the value for SUC_USER.IDCARD
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_USER.IS_VERIFIED_IDCARD
     *
     * @return the value of SUC_USER.IS_VERIFIED_IDCARD
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public Boolean getIsVerifiedIdcard() {
        return isVerifiedIdcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_USER.IS_VERIFIED_IDCARD
     *
     * @param isVerifiedIdcard the value for SUC_USER.IS_VERIFIED_IDCARD
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setIsVerifiedIdcard(Boolean isVerifiedIdcard) {
        this.isVerifiedIdcard = isVerifiedIdcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_USER.EMAIL
     *
     * @return the value of SUC_USER.EMAIL
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_USER.EMAIL
     *
     * @param email the value for SUC_USER.EMAIL
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_USER.IS_VERIFIED_EMAIL
     *
     * @return the value of SUC_USER.IS_VERIFIED_EMAIL
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public Boolean getIsVerifiedEmail() {
        return isVerifiedEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_USER.IS_VERIFIED_EMAIL
     *
     * @param isVerifiedEmail the value for SUC_USER.IS_VERIFIED_EMAIL
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setIsVerifiedEmail(Boolean isVerifiedEmail) {
        this.isVerifiedEmail = isVerifiedEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_USER.MOBILE
     *
     * @return the value of SUC_USER.MOBILE
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_USER.MOBILE
     *
     * @param mobile the value for SUC_USER.MOBILE
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_USER.IS_VERIFIED_MOBILE
     *
     * @return the value of SUC_USER.IS_VERIFIED_MOBILE
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public Boolean getIsVerifiedMobile() {
        return isVerifiedMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_USER.IS_VERIFIED_MOBILE
     *
     * @param isVerifiedMobile the value for SUC_USER.IS_VERIFIED_MOBILE
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setIsVerifiedMobile(Boolean isVerifiedMobile) {
        this.isVerifiedMobile = isVerifiedMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_USER.QQ_ID
     *
     * @return the value of SUC_USER.QQ_ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public String getQqId() {
        return qqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_USER.QQ_ID
     *
     * @param qqId the value for SUC_USER.QQ_ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setQqId(String qqId) {
        this.qqId = qqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_USER.QQ_NICKNAME
     *
     * @return the value of SUC_USER.QQ_NICKNAME
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public String getQqNickname() {
        return qqNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_USER.QQ_NICKNAME
     *
     * @param qqNickname the value for SUC_USER.QQ_NICKNAME
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setQqNickname(String qqNickname) {
        this.qqNickname = qqNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_USER.QQ_FACE
     *
     * @return the value of SUC_USER.QQ_FACE
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public String getQqFace() {
        return qqFace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_USER.QQ_FACE
     *
     * @param qqFace the value for SUC_USER.QQ_FACE
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setQqFace(String qqFace) {
        this.qqFace = qqFace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_USER.WX_ID
     *
     * @return the value of SUC_USER.WX_ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public String getWxId() {
        return wxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_USER.WX_ID
     *
     * @param wxId the value for SUC_USER.WX_ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setWxId(String wxId) {
        this.wxId = wxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_USER.WX_NICKNAME
     *
     * @return the value of SUC_USER.WX_NICKNAME
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public String getWxNickname() {
        return wxNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_USER.WX_NICKNAME
     *
     * @param wxNickname the value for SUC_USER.WX_NICKNAME
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setWxNickname(String wxNickname) {
        this.wxNickname = wxNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_USER.WX_FACE
     *
     * @return the value of SUC_USER.WX_FACE
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public String getWxFace() {
        return wxFace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_USER.WX_FACE
     *
     * @param wxFace the value for SUC_USER.WX_FACE
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setWxFace(String wxFace) {
        this.wxFace = wxFace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_USER.IS_LOCK
     *
     * @return the value of SUC_USER.IS_LOCK
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public Boolean getIsLock() {
        return isLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_USER.IS_LOCK
     *
     * @param isLock the value for SUC_USER.IS_LOCK
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setIsLock(Boolean isLock) {
        this.isLock = isLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_USER.MODIFIED_TIMESTAMP
     *
     * @return the value of SUC_USER.MODIFIED_TIMESTAMP
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public Long getModifiedTimestamp() {
        return modifiedTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_USER.MODIFIED_TIMESTAMP
     *
     * @param modifiedTimestamp the value for SUC_USER.MODIFIED_TIMESTAMP
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setModifiedTimestamp(Long modifiedTimestamp) {
        this.modifiedTimestamp = modifiedTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_USER
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", loginName=").append(loginName);
        sb.append(", loginPswd=").append(loginPswd);
        sb.append(", payPswd=").append(payPswd);
        sb.append(", salt=").append(salt);
        sb.append(", nickname=").append(nickname);
        sb.append(", face=").append(face);
        sb.append(", realname=").append(realname);
        sb.append(", isVerifiedRealname=").append(isVerifiedRealname);
        sb.append(", idcard=").append(idcard);
        sb.append(", isVerifiedIdcard=").append(isVerifiedIdcard);
        sb.append(", email=").append(email);
        sb.append(", isVerifiedEmail=").append(isVerifiedEmail);
        sb.append(", mobile=").append(mobile);
        sb.append(", isVerifiedMobile=").append(isVerifiedMobile);
        sb.append(", qqId=").append(qqId);
        sb.append(", qqNickname=").append(qqNickname);
        sb.append(", qqFace=").append(qqFace);
        sb.append(", wxId=").append(wxId);
        sb.append(", wxNickname=").append(wxNickname);
        sb.append(", wxFace=").append(wxFace);
        sb.append(", isLock=").append(isLock);
        sb.append(", modifiedTimestamp=").append(modifiedTimestamp);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_USER
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SucUserMo other = (SucUserMo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
        ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_USER
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}