package rebue.suc.mo;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

/**
 * Database Table Remarks:
 *   用户名敏感词
 *   用户名敏感词汇信息表，就是注册登录账号不能用的词汇
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table SUC_USER_FORBIDDEN_WORD
 *
 * @mbg.generated do_not_delete_during_merge 2018-02-25 16:21:26
 */
@ApiModel(value = "SucUserForbiddenWordMo", description = "用户名敏感词\n"
             +"用户名敏感词汇信息表，就是注册登录账号不能用的词汇")
@JsonInclude(Include.NON_NULL)
public class SucUserForbiddenWordMo implements Serializable {
    /**
     * Database Column Remarks:
     *   用户名敏感词ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_USER_FORBIDDEN_WORD.ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "用户名敏感词ID")
    private Long id;

    /**
     * Database Column Remarks:
     *   关键字
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUC_USER_FORBIDDEN_WORD.KEYWORD
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @ApiModelProperty(value = "关键字")
    private String keyword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SUC_USER_FORBIDDEN_WORD
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_USER_FORBIDDEN_WORD.ID
     *
     * @return the value of SUC_USER_FORBIDDEN_WORD.ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_USER_FORBIDDEN_WORD.ID
     *
     * @param id the value for SUC_USER_FORBIDDEN_WORD.ID
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUC_USER_FORBIDDEN_WORD.KEYWORD
     *
     * @return the value of SUC_USER_FORBIDDEN_WORD.KEYWORD
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUC_USER_FORBIDDEN_WORD.KEYWORD
     *
     * @param keyword the value for SUC_USER_FORBIDDEN_WORD.KEYWORD
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_USER_FORBIDDEN_WORD
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", keyword=").append(keyword);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_USER_FORBIDDEN_WORD
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SucUserForbiddenWordMo other = (SucUserForbiddenWordMo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
        ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUC_USER_FORBIDDEN_WORD
     *
     * @mbg.generated 2018-02-25 16:21:26
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}