package rebue.suc.ro;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import rebue.suc.mo.SucLockLogMo;

@JsonInclude(Include.NON_NULL)
public class SucLockLogRo {

    /**
     *	This field was generated by MyBatis Generator.
     *
     * 	返回值	1:成功  -1:失败
     *
     *	@mbg.generated
     */
    private Byte result;

    /**
     *	This field was generated by MyBatis Generator.
     *
     *	返回的结果
     *
     * @mbg.generated
     */
    private String msg;

    /**
     *	This field was generated by MyBatis Generator.
     *
     *	返回的结果值
     *
     * 	@mbg.generated
     */
    private SucLockLogMo record;

    /**
     *	This field was generated by MyBatis Generator.
     *
     *	@mbg.generated
     */
    public Byte getResult() {
        return result;
    }

    /**
     *	This field was generated by MyBatis Generator.
     *
     *	@mbg.generated
     */
    public void setResult(Byte result) {
        this.result = result;
    }

    /**
     *	This field was generated by MyBatis Generator.
     *
     *	@mbg.generated
     */
    public String getMsg() {
        return msg;
    }

    /**
     *	This field was generated by MyBatis Generator.
     *
     *	@mbg.generated
     */
    public void setMsg(String msg) {
        this.msg = msg;
    }

    /**
     *	This field was generated by MyBatis Generator.
     *
     *	@mbg.generated
     */
    public SucLockLogMo getRecord() {
        return record;
    }

    /**
     *	This field was generated by MyBatis Generator.
     *
     *	@mbg.generated
     */
    public void setRecord(SucLockLogMo record) {
        this.record = record;
    }

    /**
     *	This field was generated by MyBatis Generator.
     *
     *	@mbg.generated
     */
    @Override
    public String toString() {
        return "PfmSysTo [result=" + result + ", msg=" + msg + ", record=" + record + "]";
    }
}
